export interface Ibouteillecellier {
    id:number;
    id_supreme?:number;
    nom:string;
    image:string;
    code_saq:string;
    url_saq:string;
    pays:string;
    description:string;
    url_img:string;
    prix_saq:number;
    format:any;
    type:any;
    id_mes_bouteilles:number;
    garde_jusqua:string;
    date_achat:Date;
    millesime:number;
    notes:number;
    prix:number;
    quantite:number;
    celliers_id:any;
    id_bouteille:number;
    type_vino_name:string;
    type_mes_name:string;
    id_bouteillePerso:number;
    cellier_nom:string;
    celliers_nom:string;
    nom_bouteillePerso: string;
    type_bouteillePerso: string;
    pays_bouteillePerso: string;
    format_bouteillePerso: string;
    prix_bouteillePerso: number;
    quantite_bouteillePerso: number;
    description_bouteillePerso: string;
}
